name: CI/CD

on:
  push:
    branches:
      - main

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - name: CheckOut code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Run test
        run: php cdciTest.php

    deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: |
                cd repkin0q.beget.tech/public_html
                git pull origin master